services:
  nodered:
    image: nodered/node-red:latest
    container_name: r-nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    environment:
      TZ: "Atlantic/Cape_Verde"
    depends_on:
      - timescaledb
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: r-timescaledb
    expose:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    restart: unless-stopped

volumes:
  nodered_data:
  timescaledb_data:

